exp_name: 'example_mask'

### Data path
train_data_path: 'data/train/'                    # Training data
train_label_path: 'data/example-train-label.csv' # Training label
valid_data_path: 'data/valid/'                    # Validation Data
valid_label_path: 'data/example-valid-label.csv' # Validation Label

### output path
log_dir: 'log/'
pred_dir: 'pred/'
checkpoint_dir: 'checkpoint/'

### Parameter
use_gpu: True             #
use_cpu: 1                # Number of cores to use for data loader
display_step: 2           # Std output update rate during training
test_step: 400             # Test per n step
learning_rate: 0.0001     #
max_step: 50000            # Number of steps to train
batch_size: 20            #
first_n_byte: 2000000     # First N bytes of a PE file as the input of MalConv (defualt: 2 million)
window_size: 500          # Kernel size & stride for Malconv (defualt : 500)
sample_cnt: 1             # Number of data sampled for trianing (defualt 1 = all)

model_name: malconv
enable_dos_mask: True
enable_noise: False
